services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: fluxus_db
    ports:
      - "3306:3306"
    networks:
      - fluxus-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  fluxus-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      mysql:
          condition: service_healthy
    environment:
      - PROFILE=prd
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - fluxus-network

networks:
  fluxus-network:
    driver: bridge

volumes:
  mysql-data: