-----------------| USER |-----------------

CREATE SEQUENCE SEQ_USER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USER (
    USER_ID NUMBER(19,0) NOT NULL,
    PROFESSIONAL_ID NUMBER(19,0),
    TECHNICIAN_RESPONSIBLE NUMBER(1,0) DEFAULT 0 CHECK (TECHNICIAN_RESPONSIBLE BETWEEN 0 AND 1) NOT NULL,
    LEGAL_RESPONSIBLE NUMBER(1,0) DEFAULT 0 CHECK (LEGAL_RESPONSIBLE BETWEEN 0 AND 1) NOT NULL,
    ACTIVE NUMBER(1,0) DEFAULT 0 CHECK (ACTIVE BETWEEN 0 AND 1) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    PASSWORD VARCHAR2(255 CHAR) NOT NULL,
    ROLE VARCHAR2(10 CHAR) NOT NULL,

    PRIMARY KEY (USER_ID)
);

INSERT INTO
    TBL_USER
        (USER_ID, TECHNICIAN_RESPONSIBLE, LEGAL_RESPONSIBLE, ACTIVE, EMAIL, PASSWORD, ROLE)
    VALUES
        (1, 1, 1, 1, 'admin@admin.com', '$2a$10$WavPC5NSWR9UZRfU/EDjp.0VnK/y0xjATRTOGz.A.7ymKB4eH3/Je', 'ADMIN');
        -- Password '1234abcd' after encrypt

-----------------| BANK BRANCH |-----------------

CREATE TABLE TBL_BRANCH (
    BRANCH_ID VARCHAR2(4 CHAR) NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    ADDRESS VARCHAR2(255 CHAR),
    COMPLEMENT VARCHAR2(255 CHAR),
    DISTRICT VARCHAR2(100 CHAR),
    CITY VARCHAR2(100 CHAR),
    ZIP VARCHAR2(8 CHAR),
    STATE VARCHAR2(100 CHAR),
    CONTACT_NAME VARCHAR2(100 CHAR),
    PHONE1 VARCHAR2(11 CHAR),
    PHONE2 VARCHAR2(11 char),
    EMAIL VARCHAR2(100 CHAR),

    PRIMARY KEY (BRANCH_ID)
);

-----------------| PROFESSIONAL |-----------------

CREATE SEQUENCE SEQ_PROFESSIONAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_PROFESSIONAL (
    PROFESSIONAL_ID NUMBER(19,0) NOT NULL,
    TAG VARCHAR2(5 CHAR),
    NAME VARCHAR2(100 CHAR) NOT NULL,
    CPF VARCHAR2(11 CHAR),
    BIRTHDAY DATE,
    PROFESSION VARCHAR2(50 CHAR) NOT NULL,
    PERMIT_NUMBER VARCHAR2(50 CHAR) NOT NULL,
    ASSOCIATION VARCHAR2(100 CHAR) NOT NULL,
    PHONE1 VARCHAR2(11 CHAR),
    PHONE2 VARCHAR2(11 CHAR),
    EMAIL VARCHAR2(100 CHAR),

    PRIMARY KEY (PROFESSIONAL_ID)
);

-----------------| SERVICE |-----------------

CREATE SEQUENCE SEQ_SERVICE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SERVICE (
    SERVICE_ID NUMBER(19,0) NOT NULL,
    TAG VARCHAR2(10 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(255 CHAR) NOT NULL,
    SERVICE_AMOUNT NUMBER(6,2) NOT NULL,
    MILEAGE_ALLOWANCE NUMBER(6,2) NOT NULL,

    PRIMARY KEY (SERVICE_ID)
);

-----------------| INVOICE |-----------------

CREATE SEQUENCE SEQ_INVOICE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_INVOICE (
    INVOICE_ID NUMBER(19,0) NOT NULL,
    DESCRIPTION VARCHAR2(100 CHAR) NOT NULL,
    ISSUE_DATE TIMESTAMP(6) NOT NULL,
    SUBTOTAL_SERVICE NUMBER(6,2) NOT NULL,
    SUBTOTAL_MILEAGE NUMBER(6,2) NOT NULL,
    TOTAL NUMBER(6,2) NOT NULL,

    PRIMARY KEY (INVOICE_ID)
);

-----------------| PROFILE |-----------------

CREATE TABLE TBL_PROFILE (
    PROFILE_ID NUMBER(19,0) NOT NULL,
    CNPJ VARCHAR2(14 CHAR),
    TRADING_NAME VARCHAR2(100 CHAR),
    COMPANY_NAME VARCHAR2(255 CHAR),
    STATE_ID VARCHAR2(50 CHAR),
    CITY_ID VARCHAR2(50 CHAR),
    ADDRESS VARCHAR2(255 CHAR),
    COMPLEMENT VARCHAR2(255 CHAR),
    DISTRICT VARCHAR2(100 CHAR),
    CITY VARCHAR2(100 CHAR),
    ZIP VARCHAR2(8 CHAR),
    STATE VARCHAR2(100 CHAR),
    ESTABLISHMENT_DATE DATE,
    PHONE1 VARCHAR2(11 CHAR),
    PHONE2 VARCHAR2(11 CHAR),
    EMAIL VARCHAR2(100 CHAR),
    BANK_ACCOUNT_NAME VARCHAR2(100 CHAR),
    BANK_ACCOUNT_TYPE VARCHAR2(50 CHAR),
    BANK_ACCOUNT_BRANCH VARCHAR2(10 CHAR),
    BANK_ACCOUNT_DIGIT VARCHAR2(5 CHAR),
    BANK_ACCOUNT_NUMBER VARCHAR2(20 CHAR),
    CONTRACTOR_NAME VARCHAR2(100 CHAR),
    CONTRACT_NOTICE VARCHAR2(100 CHAR),
    CONTRACT_NUMBER VARCHAR2(100 CHAR),
    CONTRACT_ESTABLISHED DATE,
    CONTRACT_START DATE,
    CONTRACT_END DATE,

    PRIMARY KEY (PROFILE_ID)
);




-----------------| ORDER |-----------------

CREATE SEQUENCE SEQ_ORDER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_ORDER (
    ORDER_ID NUMBER(19,0) NOT NULL,
    REFERENCE_CODE VARCHAR2(27 CHAR) NOT NULL,
    BRANCH_ID VARCHAR2(4 CHAR) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DEADLINE DATE NOT NULL,
    PROFESSIONAL_ID NUMBER(19,0) NOT NULL,
    SERVICE_ID NUMBER(19,0) NOT NULL,
    SERVICE_AMOUNT NUMBER(6,2) NOT NULL,
    MILEAGE_ALLOWANCE NUMBER(6,2) NOT NULL,
    SIOPI NUMBER(1,0) DEFAULT 0 CHECK (SIOPI BETWEEN 0 AND 1) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100 CHAR),
    CITY VARCHAR2(100 CHAR),
    CONTACT_NAME VARCHAR2(100 CHAR),
    CONTACT_PHONE VARCHAR2(11 CHAR),
    COORDINATES VARCHAR2(50 CHAR),
    STATUS NUMBER(1,0) NOT NULL,
    PENDING_DATE DATE,
    SURVEY_DATE DATE,
    DONE_DATE DATE,
    COMMENTS VARCHAR2(4000),
    INVOICED NUMBER(1,0) DEFAULT 0 CHECK (INVOICED BETWEEN 0 AND 1) NOT NULL,
    INVOICE_ID NUMBER(19,0),

    PRIMARY KEY (ORDER_ID)
);

-----------------| FK CONSTRAINTS |-----------------

ALTER TABLE TBL_USER
    ADD CONSTRAINT FK_USER_PROFESSIONAL_ID
        FOREIGN KEY (PROFESSIONAL_ID)
            REFERENCES TBL_PROFESSIONAL;

ALTER TABLE TBL_ORDER
    ADD CONSTRAINT FK_ORDER_BRANCH_ID
        FOREIGN KEY (BRANCH_ID)
            REFERENCES TBL_BRANCH;

ALTER TABLE TBL_ORDER
    ADD CONSTRAINT FK_ORDER_PROFESSIONAL_ID
        FOREIGN KEY (PROFESSIONAL_ID)
            REFERENCES TBL_PROFESSIONAL;

ALTER TABLE TBL_ORDER
    ADD CONSTRAINT FK_ORDER_SERVICE_ID
        FOREIGN KEY (SERVICE_ID)
            REFERENCES TBL_SERVICE;

ALTER TABLE TBL_ORDER
    ADD CONSTRAINT FK_ORDER_INVOICE_ID
        FOREIGN KEY (INVOICE_ID)
            REFERENCES TBL_INVOICE;

