# -----------------| USER |-----------------

CREATE TABLE tbl_user (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    PROFESSIONAL_ID BIGINT,
    TECHNICIAN_RESPONSIBLE TINYINT(1) DEFAULT 0 CHECK (TECHNICIAN_RESPONSIBLE BETWEEN 0 AND 1) NOT NULL,
    LEGAL_RESPONSIBLE TINYINT(1) DEFAULT 0 CHECK (LEGAL_RESPONSIBLE BETWEEN 0 AND 1) NOT NULL,
    ACTIVE TINYINT(1) DEFAULT 0 CHECK (ACTIVE BETWEEN 0 AND 1) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(10) NOT NULL,

    PRIMARY KEY (USER_ID)
);

INSERT INTO
    tbl_user
        (USER_ID, TECHNICIAN_RESPONSIBLE, LEGAL_RESPONSIBLE, ACTIVE, EMAIL, PASSWORD, ROLE)
    VALUES
        (1, 1, 1, 1, 'admin@admin.com', '$2a$10$WavPC5NSWR9UZRfU/EDjp.0VnK/y0xjATRTOGz.A.7ymKB4eH3/Je', 'ADMIN');
        -- Password '1234abcd' after encrypt

# -----------------| BANK BRANCH |-----------------

CREATE TABLE tbl_branch (
    BRANCH_ID VARCHAR(4) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    COMPLEMENT VARCHAR(255),
    DISTRICT VARCHAR(100),
    CITY VARCHAR(100),
    ZIP VARCHAR(8),
    STATE VARCHAR(100),
    CONTACT_NAME VARCHAR(100),
    PHONE1 VARCHAR(11),
    PHONE2 VARCHAR(11),
    EMAIL VARCHAR(100),

    PRIMARY KEY (BRANCH_ID)
);

# -----------------| PROFESSIONAL |-----------------

CREATE TABLE tbl_professional (
    PROFESSIONAL_ID BIGINT NOT NULL AUTO_INCREMENT,
    TAG VARCHAR(5),
    NAME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11),
    BIRTHDAY DATE,
    PROFESSION VARCHAR(50) NOT NULL,
    PERMIT_NUMBER VARCHAR(50) NOT NULL,
    ASSOCIATION VARCHAR(100) NOT NULL,
    PHONE1 VARCHAR(11),
    PHONE2 VARCHAR(11),
    EMAIL VARCHAR(100),

    PRIMARY KEY (PROFESSIONAL_ID)
);

# -----------------| SERVICE |-----------------

CREATE TABLE tbl_service (
    SERVICE_ID BIGINT NOT NULL AUTO_INCREMENT,
    TAG VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    SERVICE_AMOUNT DECIMAL(6,2) NOT NULL,
    MILEAGE_ALLOWANCE DECIMAL(6,2) NOT NULL,

    PRIMARY KEY (SERVICE_ID)
);

# -----------------| INVOICE |-----------------

CREATE TABLE tbl_invoice (
    INVOICE_ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100) NOT NULL,
    ISSUE_DATE TIMESTAMP(6) NOT NULL,
    SUBTOTAL_SERVICE DECIMAL(6,2) NOT NULL,
    SUBTOTAL_MILEAGE DECIMAL(6,2) NOT NULL,
    TOTAL DECIMAL(6,2) NOT NULL,

    PRIMARY KEY (INVOICE_ID)
);

# -----------------| PROFILE |-----------------

CREATE TABLE tbl_profile (
    PROFILE_ID BIGINT NOT NULL AUTO_INCREMENT,
    CNPJ VARCHAR(14),
    TRADING_NAME VARCHAR(100),
    COMPANY_NAME VARCHAR(255),
    STATE_ID VARCHAR(50),
    CITY_ID VARCHAR(50),
    ADDRESS VARCHAR(255),
    COMPLEMENT VARCHAR(255),
    DISTRICT VARCHAR(100),
    CITY VARCHAR(100),
    ZIP VARCHAR(8),
    STATE VARCHAR(100),
    ESTABLISHMENT_DATE DATE,
    PHONE1 VARCHAR(11),
    PHONE2 VARCHAR(11),
    EMAIL VARCHAR(100),
    BANK_ACCOUNT_NAME VARCHAR(100),
    BANK_ACCOUNT_TYPE VARCHAR(50),
    BANK_ACCOUNT_BRANCH VARCHAR(10),
    BANK_ACCOUNT_DIGIT VARCHAR(5),
    BANK_ACCOUNT_NUMBER VARCHAR(20),
    CONTRACTOR_NAME VARCHAR(100),
    CONTRACT_NOTICE VARCHAR(100),
    CONTRACT_NUMBER VARCHAR(100),
    CONTRACT_ESTABLISHED DATE,
    CONTRACT_START DATE,
    CONTRACT_END DATE,

    PRIMARY KEY (PROFILE_ID)
);

# -----------------| ORDER |-----------------

CREATE TABLE tbl_order (
    ORDER_ID BIGINT NOT NULL AUTO_INCREMENT,
    REFERENCE_CODE VARCHAR(27) NOT NULL,
    BRANCH_ID VARCHAR(4) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DEADLINE DATE NOT NULL,
    PROFESSIONAL_ID BIGINT NOT NULL,
    SERVICE_ID BIGINT NOT NULL,
    SERVICE_AMOUNT DECIMAL(6,2) NOT NULL,
    MILEAGE_ALLOWANCE DECIMAL(6,2) NOT NULL,
    SIOPI DECIMAL(1,0) DEFAULT 0 CHECK (SIOPI BETWEEN 0 AND 1) NOT NULL,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    CONTACT_NAME VARCHAR(100),
    CONTACT_PHONE VARCHAR(11),
    COORDINATES VARCHAR(50),
    STATUS DECIMAL(1,0) NOT NULL,
    PENDING_DATE DATE,
    SURVEY_DATE DATE,
    DONE_DATE DATE,
    COMMENTS VARCHAR(4000),
    INVOICED TINYINT(1) DEFAULT 0 CHECK (INVOICED BETWEEN 0 AND 1) NOT NULL,
    INVOICE_ID BIGINT,

    PRIMARY KEY (ORDER_ID)
);

# -----------------| FK CONSTRAINTS |-----------------

ALTER TABLE tbl_user
    ADD CONSTRAINT FK_USER_PROFESSIONAL_ID
        FOREIGN KEY (PROFESSIONAL_ID)
            REFERENCES tbl_professional(PROFESSIONAL_ID);

ALTER TABLE tbl_order
    ADD CONSTRAINT FK_ORDER_BRANCH_ID
        FOREIGN KEY (BRANCH_ID)
            REFERENCES tbl_branch(BRANCH_ID);

ALTER TABLE tbl_order
    ADD CONSTRAINT FK_ORDER_PROFESSIONAL_ID
        FOREIGN KEY (PROFESSIONAL_ID)
            REFERENCES tbl_professional(PROFESSIONAL_ID);

ALTER TABLE tbl_order
    ADD CONSTRAINT FK_ORDER_SERVICE_ID
        FOREIGN KEY (SERVICE_ID)
            REFERENCES tbl_service(SERVICE_ID);

ALTER TABLE tbl_order
    ADD CONSTRAINT FK_ORDER_INVOICE_ID
        FOREIGN KEY (INVOICE_ID)
            REFERENCES tbl_invoice(INVOICE_ID);